# SPDX-License-Identifier: GPL-2.0-only
#
# drivers/char/hw/Makefile
#
# Makefile for the Linux ARM cpu and cache information char driver.
#

obj-$(CONFIG_HW_ARM64_CPU_INFO) += arm64-cpu-info.o

arm64-cpu-info-objs		+= arm64-cpu.o arm64-mm.o
